[package]
name = "rustydeb"
version = "0.1.0"
edition = "2024"

[dependencies]
ar = "0.9.0"
flate2 = "1.1.1"
serde = {version ="1.0.219", features = ["derive"]}
serde_json = "1.0.140"
tar = "0.4.44"
tempfile = "3.20.0"
xz2 = "0.1.7"
